version: '3'

services:
  photozilla_client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: photozilla_client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/client
      - /client/node_modules
    networks:
      - photozilla_net
    depends_on:
      - photozilla_server

  photozilla_server:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: photozilla_server
    env_file:
      - server-config.env
    ports:
      - '5000:5000'
    volumes:
      - ./server:/server
      - /server/node_modules
    networks:
      - photozilla_net

networks:
  photozilla_net:
    name: photozilla_net
